### ISSUE TITLE
Doesn't play nice with `should`

### ISSUE THREAD

**Issue by kevinburkeshyp** [bahmutov/cache-require-paths#2]
I'm not sure exactly what's going on but if you call `mocha --require 'should'` and then write

var should = require('should')

you get a weird error. I think that's the minimum reduced version of it.

**Comment by bahmutov** [comment]
Hahaha, I _should_ investigate this

**Comment by kevinburkeshyp** [comment]
FYI - the word `should` does weird things after you require it, so the key doesn't get set properly. not sure exactly what's going on, but here is a test case:

``` javascript
var a, should;

require('cache-require-paths');

should = require('should');

a = {};

a['should'] = 'foo';

a['bar'] = 'baz';

console.log(a); // prints {'bar': 'baz'}
```

**Comment by kevinburkeshyp** [comment]
ahhhh.... it's setting a key named `should` on every dictionary that you create so you can run `foo.should.equal 'baz'` or whatever in your test. so you can't fetch it later

**Comment by bahmutov** [comment]
bad practice - modifying prototypes,

**Comment by kevinburkeshyp** [comment]
This has been fixed
